### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by m1guelpf** [uziiuzair/Pipeline#1]
Do you need any help with the project?

**Comment by uziiuzair** [comment]
Hey @m1guelpf,
I'm currently documenting how this project is supposed to work. I will definitely love any contribution you could make. 

Currently, I'm working on a way to receive the POST data and add it to the database. You could check out the code in `calls.php`

**Comment by m1guelpf** [comment]
@uziiuzair Have you through on moving to a php framework? I mean, normal php code is a bit...

**Comment by uziiuzair** [comment]
@m1guelpf definitely considered it. And I'm thinking about moving to one. I'm thinking Laravel. Do you have any suggestions?

**Comment by m1guelpf** [comment]
I am very familiar with Laravel, so if you need help, I'd love to!

**Comment by Scrumplex** [comment]
And I would be in for frontend design.

**Comment by uziiuzair** [comment]
@Scrumplex that sounds good to me :) Give me a day or two to move (port) this to Laravel so that we can all start contributing to the project. I'll hit you guys up once I have it ready on laravel :)

**Comment by owenvoke** [comment]
I'd love to help too 😛 Looks pretty cool so far. 😄

P.S. The code uses a different table to the SQL file. Also, please don't use non-hashed passwords...
```php
mysqli_query($connection, "select * from users where password='$password' AND username='$username'");
```

**Comment by uziiuzair** [comment]
@PXgamer Hey! This is actually the first project that I did from scratch 😆  The non-hashed password was something I was only for testing purpose. I was supposed to fix that before pushing it here 😛 Anyway, working on moving this to Laravel! Can't wait to work on this with all of you!! Super excited!!!

**Comment by uziiuzair** [comment]
Hey everyone! I decided it would be better if we stay on the same custom platform. Somehow I believe adding a framework (although the better choice) might make it a little bloated. What do you guys say?

**Comment by owenvoke** [comment]
@uziiuzair to be honest I agree. Laravel is a little bit over the top for something relatively small 😃 But it's your choice.

**Comment by uziiuzair** [comment]
@PXgamer Exactly what I thought. Although using Laravel might help us in the long run. But I believe we can do better without a framework. I'm working on the Read Me right now 😃 I'll add some documentation shortly.

I have created a [Slack page](https://pipelinesteam.slack.com/shared_invite/MTQ2MjkwNDgyMTkzLTE0ODgyMTEyMzctM2FmMWJkODg0Mw) is you guys are interested on communicating there.

**Comment by owenvoke** [comment]
@uziiuzair Joined 😄

**Comment by m1guelpf** [comment]
@uziiuzair Joined!
If you aren't moving to a framework, at least you should consider refractoring to OOP...

**Comment by owenvoke** [comment]
@m1guelpf agreed, procedural isn't too great. :smile Should consider going PSR compliant too. :)
