### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by Gummy47** [uziiuzair/Pipeline#2]
Would like to get a glance at this if I could help, but there's absolutely no documentation to do so...

**Comment by uziiuzair** [comment]
Hey @Gummy47 
I would be writing the documentation over the weekend. have been a little busy to work on this project :) I'll hit you up when I have the readme.

**Comment by Gummy47** [comment]
Sure, anytime

**Comment by Gummy47** [comment]
Okay, although this issue can be closed now, what are the current TODOs for Pipeline?

**Comment by uziiuzair** [comment]
Hey @Gummy47 you can join us on our slack page! 

https://pipelinesteam.slack.com/shared_invite/MTQ2MjkwNDgyMTkzLTE0ODgyMTEyMzctM2FmMWJkODg0Mw

Currently, Im working with the new collabs to make a default way to receive post requests using the calls.php file
